# Header
menu:
  bitponics: /
  # Archives: /blog/archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tag
- tagcloud
- archive

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
